inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

RSpec/ExampleLength:
  Max: 13

RSpec/MultipleExpectations:
  Max: 5
